export const dummyEmployees = [
  {
    email: "magreth@gmail.com",
    firstName: "Magreth",
    lastName: "Steven",
    phone: "0742164660",
    uid: "AwreJwSv7EeX4AFohmyIQI8Hutw1",
    gender: "female",
    role: "admin",
  },
  {
    email: "augue@protonmail.org",
    firstName: "Kiona",
    lastName: "Robert",
    phone: "1-179-631-1771",
    uid: 2,
    gender: "female",
    role: "staff",
  },
  {
    email: "duis@aol.org",
    firstName: "Macaulay",
    lastName: "Ursula",
    phone: "557-0096",
    uid: 8,
    gender: "female",
    role: "staff",
  },
  {
    email: "et.ultrices@aol.edu",
    firstName: "Macaulay",
    lastName: "Damian",
    phone: "534-0763",
    uid: 47,
    gender: "male",
    role: "admin",
  },
  {
    email: "in@hotmail.couk",
    firstName: "Cedric",
    lastName: "Richard",
    phone: "1-566-591-2157",
    uid: 5,
    gender: "male",
    role: "staff",
  },
  {
    email: "nec.urna@aol.couk",
    firstName: "Martina",
    lastName: "Norman",
    phone: "1-525-813-8588",
    uid: 23,
    gender: "female",
    role: "staff",
  },
];
